const movies = [
  {
    id: 1,
    image: "https://m.media-amazon.com/images/I/91RGNFdfouL._AC_UL320_.jpg",
    title: "Vettaiyan",
    language: "English",
    cost: 290,
  },
  {
    id: 2,
    image: "https://m.media-amazon.com/images/I/81qnPnkyqZL._AC_UL320_.jpg",
    title: "Black tamil",
    language: "English",
    cost: 290,
  },
  {
    id: 3,
    image: "https://m.media-amazon.com/images/I/81hSDsdtu0L._AC_UL320_.jpg",
    title: "Jailer",
    language: "English",
    cost: 290,
  },
  {
    id: 4,
    image: "https://m.media-amazon.com/images/I/81+noTP8OML._AC_UL320_.jpg",
    title: "malyalam movies",
    language: "English",
    cost: 290,
  },
  {
    id: 5,
    image: "https://m.media-amazon.com/images/I/91+ULs4-VFL._AC_UL320_.jpg",
    title: "Razzi",
    language: "English",
    cost: 290,
  },
  {
    id: 6,
    image: "https://m.media-amazon.com/images/I/91F9AIG6wqL._AC_UL320_.jpg",
    title: "ismart",
    language: "English",
    cost: 290,
  },
  {
    id: 7,
    image: " https://m.media-amazon.com/images/I/91STiltuxdL._AC_UL320_.jpg",
    title: "Dhrishyam2",
    language: "English",
    cost: 290,
  },
  {
    id: 8,
    image: "https://m.media-amazon.com/images/I/91WSoBlKCrL._AC_UL320_.jpg",
    title: "tiger3",
    language: "English",
    cost: 290,
  },
  {
    id: 9,
    image: "https://m.media-amazon.com/images/I/81XnLB3yD8L._AC_UL320_.jpg",
    title: "Chandu champian",
    language: "English",
    cost: 290,
  },
  {
    id: 10,
    image: "https://m.media-amazon.com/images/I/81y16BTH23L._AC_UL320_.jpg",
    title: "Hitler",
    language: "English",
    cost: 290,
  },
];
export default movies;
